### ISSUE TITLE
DLMSClient fails to parse push message objects

### ISSUE THREAD

**Issue by TheSamabo** [Gurux/Gurux.DLMS.Python#30]
Hello!

I've been testing Iskramaeco AM550 Push message feature when i found a problem with DLMSClient.
I wanted to try and use the parsePushObjects function to decode the fields and values in the push message.
After i added the setup object to the push message object list it threw : `Traceback (most recent call last):
  File "main.py", line 98, in onReceived
    objects = self.client.parsePushObjects(self.notify.value[0])
  File "/home/samuel/.local/lib/python3.8/site-packages/gurux_dlms/GXDLMSClient.py", line 1258, in parsePushObjects
    if classID > 0:
TypeError: '>' not supported between instances of 'GXStructure' and 'int'`

im also gonna paste here the parsed version of the message: `[bytearray(b'\x00\x01\x19\t\x00\xff'), [[40, bytearray(b'\x00\x01\x19\t\x00\xff'), 0, 0], [1, bytearray(b'\x01\x00\x00\t\x02\xff'), 2, 0], [1, bytearray(b'\x01\x00\x00\t\x01\xff'), 2, 0], [3, bytearray(b'\x01\x00 \x07\x00\xff'), 2, 0], [3, bytearray(b'\x01\x004\x07\x00\xff'), 2, 0], [3, bytearray(b'\x01\x00H\x07\x00\xff'), 2, 0]], [0, bytearray(b'<myStaticIPaddress>'), 0], [], 0, 0, 0]`

Thank you!

**Comment by TheSamabo** [comment]
Okay never mind i found the problem was that i didn't use correct attribute for Push Setup in object list
