### ISSUE TITLE
Object is not subscriptable

### ISSUE THREAD

**Issue by martink173** [Gurux/Gurux.DLMS.Python#36]
```
DEBUG:smartmeter:DLMS packet complete and ready for parsing.
bytearray(b'\x07\xe5\x0c\n\x05\x15\x17\x00\xff\x80\x00\x00')
7
INFO:root:App shutting down now.
DEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
Traceback (most recent call last):
  File "./smartmeter-datacollector", line 14, in <module>
    app.main()
  File "/home/pi/.local/lib/python3.7/site-packages/smartmeter_datacollector/app.py", line 69, in main
    asyncio.run(build_and_start(app_config), debug=debug_mode)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/smartmeter_datacollector/app.py", line 29, in build_and_start
    data_collector.process_queue())
  File "/home/pi/.local/lib/python3.7/site-packages/smartmeter_datacollector/smartmeter/meter.py", line 46, in start
    await self._serial.start_and_listen()
  File "/home/pi/.local/lib/python3.7/site-packages/smartmeter_datacollector/smartmeter/serial_reader.py", line 45, in start_and_listen
    self._callback(data)
  File "/home/pi/.local/lib/python3.7/site-packages/smartmeter_datacollector/smartmeter/meter.py", line 57, in _data_received
    dlms_objects = self._parser.parse_to_dlms_objects()
  File "/home/pi/.local/lib/python3.7/site-packages/smartmeter_datacollector/smartmeter/hdlc_dlms_parser.py", line 84, in parse_to_dlms_objects
    parsed_objects = self._client.parsePushObjects(self._dlms_data.value[0])
  File "/home/pi/.local/lib/python3.7/site-packages/gurux_dlms/GXDLMSClient.py", line 1262, in parsePushObjects
    comp = self.objects.findByLN(classID, _GXCommon.toLogicalName(tmp[1]))
TypeError: 'int' object is not subscriptable
```

I printed the byte array for debugging... The code receives 3 DLMS PDUs, then stops at parsePushObjects
Any ideas?

**Comment by gurux01** [comment]
Hello,

You can ask this in Gurux forum.
